### ISSUE TITLE
Preview doesn't show the latests changes.

### ISSUE THREAD

**Issue by marcorivm** [ericlbarnes/wardrobe#64] opened 2013-08-08 17:47 UTC
When editing a Post the preview button should show a preview according to the current state of the document, currently it shows the latest published version, so a user needs to click "Publish post" before being able to watch the preview, for me the preview should show my changes before I publish the post, so I'm sure that's the way I want it to look.

**Comment by ericlbarnes** [comment] 2013-08-08 18:58
The way it was designed is say you are writing a post and you want to see what it looks like. So you then set the status to draft then save it and preview. That way it isn't live.  Once it's live I didn't really see a benefit of previewing just the new changes. Might be just me. :smile: 

The whole feature would need to be redesigned to switch it over to accepting post data instead of pulling from the db which would be really messy.

**Comment by marcorivm** [comment] 2013-08-09 19:15
Imagine the case where you are editing an already existing post, you have some info to update and new stuff to add, you would need to make a copy of the post for editing and saving it as a draft since saving the original post as a draft would remove it from the feed, now you need to save each change, which might not be what was intended (that's why we are looking at the preview to verify it's OK) and then only then you can look at the preview.

I don't know if that makes sense.

**Comment by jeremykendall** [comment] 2013-08-09 22:42
I agree with @marcorivm.  It's important to be able to watch how the document changes as you're editing, both before and after being published.  As I'm writing, I want to be able to hit the preview button and see what work I've done so far.  That's _especially_ important with already published posts.

You might not have to go the route of pulling `$_POST` data to preview the document in its current state.  You may need an additional table, however, to save a "draft" or "in progress" version of documents to allow for that.  That's just off the top of my head, but it might be a better avenue than trying to handle request data as a data source for preview.  That sounds really scary, from a data loss perspective.

**Comment by ericlbarnes** [comment] 2013-08-10 00:05
Let me do some thinking on this and see if I can come up with something suitable.

**Comment by jeremykendall** [comment] 2013-08-10 02:16
Perhaps you could implement something like this?  Click "Preview" and:
- If post has never been saved, or is marked as draft, save the post and then display preview
- If the post has been published, save the post to a drafts table (?) and then display preview

**Comment by ericlbarnes** [comment] 2013-08-11 03:10
I started researching this tonight and I think I have a suitable work around. See the following screencast and please give me your thoughts. 
http://screencast.com/t/1UARkePzQ

**Comment by jeremykendall** [comment] 2013-08-12 14:16
@ericbarnes Wow! What sort of dark magick is that?! ;-)

That's nice, but what happens if I just write, save, and hit preview?

**Comment by ericlbarnes** [comment] 2013-08-12 14:24
I am not storing drafts so when you hit save it's still going to really save it. So with this change you just write and then hit preview. Once you are happy then save it. 

Behind the scenes what I am doing is using a pub/sub with browsers local storage and reading that in the preview template. That way it will update real time and give you that instant feedback on your changes. 

This should also have the secondary benefit of being able to preview new posts which isn't currently possible.

**Comment by rtablada** [comment] 2013-08-12 14:30
This should still allow a timeout to save drafts to cache as well which will be nice.

**Comment by marcorivm** [comment] 2013-08-12 14:36
Looks great, but I think the url should only be "preview", and keep the ID when viewing the saved state of a document.

**Comment by ericlbarnes** [comment] 2013-08-12 14:38
@rtablada What is the benefit of saving to a real cache file? I'm not seeing why that would be useful. 

@marcorivm It uses the id so if you have more than post open (such as multiple tabs) it knows which one you actually want to preview. Other wise how would we know?

**Comment by mpmont** [comment] 2013-08-12 15:07
@ericbarnes that looks like an amazing feature to add. Writing an article and being able to preview it live on my template would be amazing. =)

**Comment by rtablada** [comment] 2013-08-12 15:21
The cache state with timeouts wouldn't be for previews. It would be used for drafts. I've had my Internet drop out a few times while I was writing and completely lost my progress.

As a separate feature, I would think auto save could cache off a draft for each user, then this cache clears when you actually save the doc?

**Comment by ericlbarnes** [comment] 2013-08-13 00:45
I just implemented these in [core](https://github.com/wardrobecms/core) using local storage. I really think that is going to be easier than doing on the server end. To test it just start writing a new post and then refresh. It should currently keep everything except the status which I need to account for. Under the hood it basically does what you proposed and clears it once the post is saved.

**Closed as completed** 2013-08-14 12:12 UTC
