### ISSUE TITLE
SQLite Error when inserting new post

### ISSUE THREAD

**Issue by moshohayeb** [ericlbarnes/wardrobe#27] opened 2013-06-22 11:54 UTC
Hello, I get the following error when trying to write a new blog post:
Error:
Object: object

**Comment by ericlbarnes** [comment] 2013-06-22 15:27
Can you view the logs and see what the actual error is?  Should have an exception thrown in the api/postcontroller

**Comment by moshohayeb** [comment] 2013-06-22 19:34
Hi, here is the full log
http://pastebin.com/ZcwC2TBz

**Comment by ericlbarnes** [comment] 2013-06-22 23:36
```
table posts has no column named publish_date
```

Looks like maybe it didn't install properly. I would drop the db and install again.

**Comment by ericlbarnes** [comment] 2013-06-23 20:26
Closing but please follow up if this doesn't fix it.

**Comment by grena** [comment] 2013-07-06 00:44
I can confirm, the problem is not fixed :
`table posts has no column named publish_date`
when trying to publish a new post.

Viewing the sqlite file, here is the **posts** table :

```
0|id|integer|0||1
1|title|varchar|0||0
2|slug|varchar|0||0
3|content|text|0||0
4|image|varchar|0||0
5|type|varchar|0||0
6|active|integer|0|'0'|0
7|created_at|datetime|0||0
8|updated_at|datetime|0||0
```

So yes, there's no **publish_date** field.

**Comment by ericlbarnes** [comment] 2013-07-06 04:46
@grena Did you just install wardrobe? It appears I added that col on june 4th. 
https://github.com/ericbarnes/wardrobe/blob/master/app/database/migrations/2013_05_31_140553_create_posts_table.php#L22

Does anything stand out to you that would cause that field to not be added when the migration is added?

**Comment by grena** [comment] 2013-07-06 11:13
Hello @ericbarnes,
Yes I just did a fresh install yesterday by cloning the repo. Here are the steps I did 

```
git clone https://github.com/ericbarnes/wardrobe.git myproject && cd myproject
composer.phar install
**Here  I changed app/config/database.php to switch to sqlite**
cd ..
chown -R www-data:www-data myproject
```

And I ran the installation.  
Did I miss a step ?

**Comment by ericlbarnes** [comment] 2013-07-06 23:45
Looks correct. I will do some testing and see whats up.

**Comment by ericlbarnes** [comment] 2013-07-07 00:03
I just did a fresh install with sqlite and didn't have any issues. See the publish_date? 

![img](http://dl.dropboxusercontent.com/u/2880058/Screenshots/87.png)

You have any thoughts on what the issue could be?

**Closed as completed by ericlbarnes** 2013-07-07 00:03 UTC

**Comment by ericlbarnes** [comment] 2013-07-07 00:08
Sorry for spamming the thread :) I think I have it figured it out now. The default sqlite file wasn't empty from when I first started building the app. So the migration never ran since all the tables was already created.

**Comment by grena** [comment] 2013-07-07 11:47
Hi,
I just tested right now and it works, the bug is fixed :)
Thank you for your investigation !
Cheers.
